[versions]
agp = "8.13.2"
android_cn_oaidVersion = "4.2.16"
comGoogleCodeGsonGson = "2.13.1"
coreSplashscreenVersion = "1.2.0"
flexboxVersion = "3.0.0"
glide = "5.0.5"
javase = "3.5.4"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.7.0"
materialVersion = "1.14.0-alpha04"
activity = "1.12.2"
constraintlayout = "2.2.1"
okhttp = "5.3.2"
sensebot = "4.4.4"
touchimageview = "3.7.1"
ucrop = "2.2.11"

[libraries]
com-google-code-gson-gson3 = { module = "com.google.code.gson:gson", version.ref = "comGoogleCodeGsonGson" }
core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreenVersion" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
google-flexbox = { module = "com.google.android.flexbox:flexbox", version.ref = "flexboxVersion" }
gzu-liyujiang-android_cn_oaid = { module = "com.github.gzu-liyujiang:Android_CN_OAID", version.ref = "android_cn_oaidVersion" }
javase = { module = "com.google.zxing:javase", version.ref = "javase" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material-v1140alpha04 = { module = "com.google.android.material:material", version.ref = "materialVersion" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
sensebot = { module = "com.geetest.sensebot:sensebot", version.ref = "sensebot" }
touchimageview = { module = "com.github.MikeOrtiz:TouchImageView", version.ref = "touchimageview" }
ucrop = { module = "com.github.yalantis:ucrop", version.ref = "ucrop" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

